### PR TITLE
Add EditorConfig

### PR DESCRIPTION
**Pull request by hyperupcall**
As alluded to in [this PR](https://github.com/tofuutils/tofuenv/pull/58), this adds an EditorConfig. It's similar to that in the original PR, except the default indent_style was changed to tab, since the majority of the code is written in Go.  The rest of the file is written as a result.

FYI: The link in `.github/CONTRIBUTING.md` is broken

### CODE REVIEW

**Comment by dvaumoron** [comment]
Go has its own formatting rules, so maybe *.go file should be excluded

**Comment by kvendingoldo** [comment]
agree about go

**Comment by hyperupcall** [comment]
Are there any specific rules that you would like to be excluded? As long as the default Go formatting rules don't contradict the EditorConfig, then contributors will still automatically get the correct file editing settings. If Go is excluded as a whole, then settings may be incorrect on type, and only fixed if `go fmt` is ran. Here is an [example of an EditorConfig in kubernetes/dashboard](https://github.com/kubernetes/dashboard/blob/master/.editorconfig) that seems to work well.

**Comment by dvaumoron** [comment]
That's not my point, an editor supporting Go should already enforce Go formatting rules with `go fmt` on save, so a second check does not seem useful

**Pull request closed without merging**
