### PR TITLE
feat: min-required fallback to minimum

### PR DESCRIPTION
**Pull request by apeabody**
Rather than latest, it would be useful if min-required could fallback to a minimum version.

### CODE REVIEW

**Comment by kvendingoldo** [comment]
Good idea!

**Comment by dvaumoron** [comment]
I believe a minimum version search without requirement could lead to issues (I don't even know what is the minimum available version of Terraform and which feature exist in that version).

**Comment by apeabody** [comment]
> I believe a minimum version search without requirement could lead to issues (I don't even know what is the minimum available version of Terraform and which feature exist in that version).

Thanks @kvendingoldo & @dvaumoron!

I agree this could certainly lead to issues.  My current preference would be an option to:
- use/install min-required
- failing that: try TFENV_TERRAFORM_DEFAULT_VERSION
- failing that: latest strategy, etc

This basically let's someone specific a fallback minimum rather than searching indiscriminately for a minimum.  That said this option doesn't appear to work for me even when setting TFENV_TERRAFORM_DEFAULT_VERSION, if a minimum isn't discovered in .tf, it uses the latest strategy which generally ends up using the newest version (which I already have installed).

**Comment by dvaumoron** [comment]
What do you try to achieve ? You can use `tenv tf constraint` to ensure a minimum version (as in `tenv tf constraint ">= 1.2.0"`).

See the resolution order [here](https://github.com/tofuutils/tenv#project-binaries).

**Comment by apeabody** [comment]
> What do you try to achieve ? You can use `tenv tf constraint` to ensure a minimum version (as in `tenv tf constraint ">= 1.2.0"`).
> 
> See the resolution order [here](https://github.com/tofuutils/tenv#project-binaries).

Hi @dvaumoron - Thanks for the resolution order!

Yes, I was trying to use `TFENV_TERRAFORM_DEFAULT_VERSION` to accomplish.  Which appears should work from the resolution order.  However I'm not seeing the expected behavior.

```
TFENV_TERRAFORM_DEFAULT_VERSION=0.13.7 tenv tf use min-required -v

Scan project to find .tf files
2024-05-06T18:37:08.821Z [DEBUG] tenv: Read: filePaths=["main.tf"]
2024-05-06T18:37:08.821Z [DEBUG] tenv: Failed to read file: error="open /home/runner/.tenv/Terraform/constraint: no such file or directory"
2024-05-06T18:37:08.821Z [DEBUG] tenv: Find: constraints=[]
No Terraform version requirement found in project files, fallback to latest strategy
Found compatible version installed locally : 1.7.0
Written 1.7.0 in /home/runner/.tenv/Terraform/version
```

In this example I would have expected it to use Terraform `0.13.7`.

**Comment by dvaumoron** [comment]
Your command contains the argument `min-required` as the strategy to find the version of Terraform to use. So it does not call the resolution behavior to know which version, constraint or strategy must be used to find a correct version.

Morevover `TFENV_TERRAFORM_DEFAULT_VERSION` is meant to allow a fallback when there is no version information in `.terraform-version` file (or other equivalent).

Finally ensuring use of version 0.13.7 with `min-required` strategy can be done with `TFENV_TERRAFORM_DEFAULT_CONSTRAINT=">= 0.13.7"`

**Comment by apeabody** [comment]
> Your command contains the argument `min-required` as the strategy to find the version of Terraform to use. So it does not call the resolution behavior to know which version, constraint or strategy must be used to find a correct version.
> 
> Morevover `TFENV_TERRAFORM_DEFAULT_VERSION` is meant to allow a fallback when there is no version information in `.terraform-version` file (or other equivalent).
> 
> Finally ensuring use of version 0.13.7 with `min-required` strategy can be done with `TFENV_TERRAFORM_DEFAULT_CONSTRAINT=">= 0.13.7"`

Thanks @dvaumoron! - Yes, using `TFENV_TERRAFORM_DEFAULT_CONSTRAINT=">= 0.13.7"` with `min-required` appears to work as desired.  Thanks Again!

**Comment by kvendingoldo** [comment]
@apeabody can you add this case to README.md, if it is not difficult for u?

**Pull request closed without merging**
