### PR TITLE
fix: Improve type checks in extractReleases

### PR DESCRIPTION
**Pull request by Abhinavcode13**
- Original reused object for maps, revised uses versions.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
CC : @kvendingoldo

**Comment by kvendingoldo** [comment]
Looks fine from my side, @dvaumoron please check it.

**Comment by Abhinavcode13** [comment]
Still DCO CI - failed.

**Comment by kvendingoldo** [comment]
yep. You can fix it by the following commands:
$ git rebase HEAD~3 --signoff 
$ git push --force-with-lease origin main

**Review by dvaumoron — COMMENTED** [review]
This change is not mandatory, if value does not contain the correct type `object` will get the default value (a `nil `map), then the `object["versions"]` will be `nil` too and object will stay `nil` and `ok` will be false, then the function will return without `panic`.

**Comment by Abhinavcode13** [comment]
I understand that the default nil values prevent a panic. However, I included explicit type assertions for `map[string]any` to make the function's behavior more predictable.

**Comment by dvaumoron** [comment]
Hi @Abhinavcode13,

Among my commit today, I changed to create a `versions` variable in place of reassigning object, to make the code more understandable, however I still did not want to add unnecessary line for an earlier return.

If you are willing to contribute officially, take care of the DCO check, it would have allowed me to merge your proposal and modify the code afterward.

thanks for pointing out

**Pull request closed without merging**
